server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

          routes:
            - id: media-service
              uri: lb://MEDIA-SERVICE
              predicates:
                - Path=/api/v1/media/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/